apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrack-app
  labels:
    app: metrack
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metrack
  template:
    metadata:
      labels:
        app: metrack
    spec:
      containers:
        - name: metrack-container
          image: garudaone/metrackv1:latest
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "3000"
---
apiVersion: v1
kind: Service
metadata:
  name: metrack-service
spec:
  type: NodePort
  selector:
    app: metrack
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001