apiVersion: apps/v1
kind: Deployment
metadata:
  name: met-app
  labels:
    app: met-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: met-app
  template:
    metadata:
      labels:
        app: met-app
    spec:
      containers:
        - name: met-app
          image: garudaone/met-app:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
