apiVersion: v1
kind: Service
metadata:
  name: met-app
  labels:
    app: met-app
spec:
  type: ClusterIP
  selector:
    app: met-app
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP